FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install python3 and GCC openmp (Depends with cryptFlow2 library)
RUN apt-get update \
  && apt-get install -y python3 python3-dev libgmp-dev python3-pip tzdata wget libmysqlclient-dev \
  && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY fediux-linux-amd64.tar.gz fediux-linux-arm64.tar.gz /opt/
COPY src/fediux/protos/ src/fediux/protos/

RUN tar zxf /opt/fediux-linux-$(dpkg --print-architecture).tar.gz \
  && mkdir log
RUN ln -s -f bazel-bin/cli fediux-cli
RUN ln -s -f bazel-bin/node fediux-node
WORKDIR /app/python

RUN python3 -m pip install --upgrade pip \
  && python3 -m pip install -r requirements.txt \
  && if [ "$(dpkg --print-architecture)" = "arm64" ]; then \
     wget https://fediux.oss-cn-beijing.aliyuncs.com/dev/tenseal-0.3.14-cp38-cp38-linux_aarch64.whl \
     && pip install tenseal-0.3.14-cp38-cp38-linux_aarch64.whl; \
     fi \
  && python3 setup.py install \
  && rm -rf /root/.cache/pip/

WORKDIR /app

# gRPC server port
EXPOSE 50050