# Call this Dockerfile via the build_local.sh script
FROM fediux/fediux-base

WORKDIR /app

ADD bazel-bin.tar.gz ./
COPY src/fediux/protos/ src/fediux/protos/
RUN ln -s -f bazel-bin/cli fediux-cli
RUN ln -s -f bazel-bin/node fediux-node
RUN mkdir log \
  && cd python \
  && python3 setup.py develop

EXPOSE 50050
