package(default_visibility = ["//visibility:public"])
cc_library(
  name = "psi_util",
  hdrs = ["util.h"],
  srcs = ["util.cc"],
  deps = [
    "//src/fediux/common:common_defination",
    "//src/fediux/data_store:data_store_lib",
    "@arrow",
  ],
)